[package]
name = "market_data_time_series"
version = "0.1.0"
authors = ["Konstantin Đorđević <vomindoraan@gmail.com>", "Filip Dulić <filip.dulic@gmail.com>"]

[dependencies]
influx_db_client = "^0.3.6"
protobuf = "2.2.0"
zmq = "0.8"

[[bin]]
name = "main"
doc = false
